server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/ledger}
  cloud:
    gateway:
      routes:
        - id: ledger-transactions
          uri: ${LEDGER_SERVICE_URL:http://localhost:8090}
          predicates:
            - Path=/transactions/**
        - id: ledger-reconciliation
          uri: ${LEDGER_SERVICE_URL:http://localhost:8090}
          predicates:
            - Path=/reconciliation/**
        - id: holds
          uri: ${HOLDS_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/holds/**
        - id: holds-available-balance
          uri: ${HOLDS_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/accounts/*/available-balance
        - id: fx-rates
          uri: ${FX_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/rates/**
        - id: fx-conversions
          uri: ${FX_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/conversions/**
        - id: ledger-accounts
          uri: ${LEDGER_SERVICE_URL:http://localhost:8090}
          predicates:
            - Path=/accounts/**
        - id: ledger-wallets
          uri: ${LEDGER_SERVICE_URL:http://localhost:8090}
          predicates:
            - Path=/wallets/**
        - id: ledger-transfers
          uri: ${LEDGER_SERVICE_URL:http://localhost:8090}
          predicates:
            - Path=/transfers/**

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health
  metrics:
    tags:
      application: ${spring.application.name}
