global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ledger-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ledger-service:8090']
  - job_name: 'transaction-processor'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['transaction-processor:8081']
  - job_name: 'holds-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['holds-service:8082']
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']
  - job_name: 'fx-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['fx-service:8083']
